---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
data:
  MLFLOW_TRACKING_URI: "sqlite:///mlflow.db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
    component: mlflow-tracking-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 0
        runAsNonRoot: false

      containers:
        - name: mlflow
          image: python:3.11-slim
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            privileged: false
            capabilities:
              drop: ["ALL"]
            runAsUser: 0

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "5Gi"

          ports:
            - containerPort: 5000
              name: http

          command: ["sh", "-c"]
          args:
            - pip install mlflow==2.9.2 && mlflow server --host 0.0.0.0 --port 5000

          envFrom:
            - configMapRef:
                name: mlflow-config

          volumeMounts:
            - name: mlflow-artifacts
              mountPath: /mlflow/artifacts
            - name: mlflow-db
              mountPath: /mlflow/mlflow.db
              subPath: mlflow.db

      volumes:
        - name: mlflow-artifacts
          persistentVolumeClaim:
            claimName: model-output-pvc
        - name: mlflow-db
          persistentVolumeClaim:
            claimName: timescale-pvc
